In [46]:
import pandas as pd
import numpy as np

In [47]:
train = pd.read_csv("train_fwYjLYX.csv",parse_dates=['application_date'])
test = pd.read_csv("test_1eLl9Yf.csv",parse_dates=['application_date'])

In [48]:
train_segment1 = train[train['segment'] == 1]
train_segment2 = train[train['segment'] == 2]

test_segment1 = test[test['segment'] == 1]
test_segment2 = test[test['segment'] == 2]

In [49]:
len(test_segment1)

87

In [53]:
train_segment1['branch_id'].nunique()

83

In [55]:
test_segment1.append([test_segment1]*2,ignore_index=True)

     id application_date  segment
0     1       2019-07-06        1
1     2       2019-07-07        1
2     3       2019-07-08        1
3     4       2019-07-09        1
4     5       2019-07-10        1
5     6       2019-07-11        1
6     7       2019-07-12        1
7     8       2019-07-13        1
8     9       2019-07-14        1
9    10       2019-07-15        1
10   11       2019-07-16        1
11   12       2019-07-17        1
12   13       2019-07-18        1
13   14       2019-07-19        1
14   15       2019-07-20        1
15   16       2019-07-21        1
16   17       2019-07-22        1
17   18       2019-07-23        1
18   19       2019-07-24        1
19   20       2019-07-25        1
20   21       2019-07-26        1
21   22       2019-07-27        1
22   23       2019-07-28        1
23   24       2019-07-29        1
24   25       2019-07-30        1
25   26       2019-07-31        1
26   27       2019-08-01        1
27   28       2019-08-02        1
28   29       2019-08-03        1
29   30       2019-08-04        1
..   ..              ...      ...
231  58       2019-09-01        1
232  59       2019-09-02        1
233  60       2019-09-03        1
234  61       2019-09-04        1
235  62       2019-09-05        1
236  63       2019-09-06        1
237  64       2019-09-07        1
238  65       2019-09-08        1
239  66       2019-09-09        1
240  67       2019-09-10        1
241  68       2019-09-11        1
242  69       2019-09-12        1
243  70       2019-09-13        1
244  71       2019-09-14        1
245  72       2019-09-15        1
246  73       2019-09-16        1
247  74       2019-09-17        1
248  75       2019-09-18        1
249  76       2019-09-19        1
250  77       2019-09-20        1
251  78       2019-09-21        1
252  79       2019-09-22        1
253  80       2019-09-23        1
254  81       2019-09-24        1
255  82       2019-09-25        1
256  83       2019-09-26        1
257  84       2019-09-27        1
258  85       2019-09-28        1
259  86       2019-09-29        1
260  87       2019-09-30        1

[261 rows x 3 columns]